name: somzcloud
channels:
  - conda-forge
dependencies:
  - rail
  - python>=3.10
  - numpy>=1.21
  - astropy
  - pandas
  - h5py=*mpi_openmpi*
  - hdf5=*mpi_openmpi*
  - healpy
  - fitsio
  - pyarrow
  - pytables
  - mpi4py
  - jax
  - jaxlib
  - somoclu
